### ISSUE TITLE
Crash with pre-generated character sheet

### ISSUE THREAD

**Issue by teejo75** [JDCain/FG5eXmlToPdf#12]
I used a pre-generated character sheet from Lost Mine of Phandelver in the current release of FG (v3.3.7). Exported the character and ran the exe:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at FG5eXmlToPDF.FG5eXml.LoadCharacter(XElement charElement) in C:\Users\jd.LOCORUM\Source\Repos\FG5eXmlToPdf\FG5eXmlToPdf\Fg5eXml.cs:line 88
   at FG5eXmlToPDF.FG5eXml.LoadCharacters(String filePath) in C:\Users\jd.LOCORUM\Source\Repos\FG5eXmlToPdf\FG5eXmlToPdf\Fg5eXml.cs:line 24
   at FG5eXmlToPdf.Console.Program.Main(String[] args)

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at FG5eXmlToPDF.FG5eXml.LoadCharacter(XElement charElement) in C:\Users\jd.LOCORUM\Source\Repos\FG5eXmlToPdf\FG5eXmlToPdf\Fg5eXml.cs:line 88
   at FG5eXmlToPDF.FG5eXml.LoadCharacters(String filePath) in C:\Users\jd.LOCORUM\Source\Repos\FG5eXmlToPdf\FG5eXmlToPdf\Fg5eXml.cs:line 24
   at FG5eXmlToPdf.Console.Program.Main(String[] args)
```

**Comment by JDCain** [comment]
Can you attach the file or link me to it? I've not got FG setup right now and I want to make sure I get the right version. 

Was it with all the sheets or a specific one?

**Comment by teejo75** [comment]
Here you go. I attached all 5. Only "char4.xml" works. The others cause the NullReferenceException.

[chars.zip](https://github.com/JDCain/FG5eXmlToPdf/files/2830917/chars.zip)

These are all exports from the current version of FG.

**Comment by JDCain** [comment]
merged in.
